config/routes.rb
Rails.application.routes.draw do
  root "pokedex#index"
  get "/search" => "pokedex#search"
  resources :pokemon
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokedex_controller.rb
class PokedexController < ApplicationController
  POKE_API_URL = "https://pokeapi.co/api/v2/pokemon/"
  def index
  end

  def search
    # params[:name]
    response = HTTParty.get(POKE_API_URL + params[:name])
    @pokemon = JSON.parse(response.body)
  end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemon or /pokemon.json
  def index
    @pokemon = Pokemon.all
  end

  # GET /pokemon/1 or /pokemon/1.json
  def show
  end

  # GET /pokemon/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemon/1/edit
  def edit
  end

  # POST /pokemon or /pokemon.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon/1 or /pokemon/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon/1 or /pokemon/1.json
  def destroy
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to pokemon_index_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:external_id, :name, :front_default_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokedex_helper.rb
module PokedexHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeapiRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokedex/index.html.erb
<h1>Pokedex</h1>
<%= form_with url: "/search", method: :get do |form| %>
  <%= form.label :name, "Pokemon Name:" %>
  <%= form.text_field :name %>

  <%= form.submit "Search" %>
<% end %>

app/views/pokedex/search.html.erb
<h1>Search Results</h1>
<div>
  <p>
    Pokemon #
    <%= @pokemon['id'] %>
  </p>

  <h2>
    <%= @pokemon['name'] %>
  </h2>

  <div>
    <%= image_tag @pokemon['sprites']['front_default'] %>
  </div>

  <%= form_with model: Pokemon, url: pokemon_index_path do |form| %>
    <%= form.hidden_field :external_id, value: @pokemon['id'] %>
    <%= form.hidden_field :name, value: @pokemon['name'] %>
    <%= form.hidden_field :front_default_image, value: @pokemon['sprites']['front_default'] %>

    <%= form.submit "Catch This Pokemon" %>
  <% end %>
</div>

app/views/pokemon/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :external_id, style: "display: block" %>
    <%= form.number_field :external_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :front_default_image, style: "display: block" %>
    <%= form.text_field :front_default_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon/_pokemon.html.erb
<div id="<%= dom_id pokemon %>">
  <p>
    <strong>External:</strong>
    <%= pokemon.external_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= pokemon.name %>
  </p>

  <p>
    <strong>Front default image:</strong>
    <%= pokemon.front_default_image %>
  </p>

</div>

app/views/pokemon/edit.html.erb
<h1>Editing pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Show this pokemon", @pokemon %> |
  <%= link_to "Back to pokemon", pokemon_index_path %>
</div>

app/views/pokemon/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokemon</h1>

<div id="pokemon">
  <% @pokemon.each do |pokemon| %>
    <%= render pokemon %>
    <p>
      <%= link_to "Show this pokemon", pokemon %>
    </p>
  <% end %>
</div>

<%= link_to "New pokemon", new_pokemon_path %>

<%= link_to "Back to Pokedex", root_url %>

app/views/pokemon/new.html.erb
<h1>New pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Back to pokemon", pokemon_index_path %>
</div>

app/views/pokemon/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokemon %>

<div>
  <%= link_to "Edit this pokemon", edit_pokemon_path(@pokemon) %> |
  <%= link_to "Back to pokemon", pokemon_index_path %>

  <%= button_to "Destroy this pokemon", @pokemon, method: :delete %>
</div>